name: Deploy Frontend to Synology NAS

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggers

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: self-hosted # This will run on your Synology NAS
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          VITE_API_URL=http://your-synology-ip:3000

    - name: Deploy Frontend to Synology
      run: |
        cd /volume1/docker/shopping-list
        
        # Pull latest frontend image
        docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        
        # Update docker-compose to use the new image
        sed -i 's|build: \.|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest|g' docker-compose.synology.yml
        
        # Update and restart frontend service
        docker-compose -f docker-compose.synology.yml pull shopping-list-frontend
        docker-compose -f docker-compose.synology.yml up -d shopping-list-frontend
        
        # Wait for frontend to be ready
        echo "Waiting for frontend to be ready..."
        for i in {1..20}; do
          if curl -f http://localhost:8080 > /dev/null 2>&1; then
            echo "Frontend is ready!"
            break
          fi
          echo "Attempt $i/20: Frontend not ready yet..."
          sleep 5
        done
        
        # Cleanup old images
        docker image prune -f

    - name: Verify deployment
      run: |
        # Test the deployment
        curl -f http://localhost:8080 || exit 1
        echo "✅ Frontend deployment successful!"

    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Frontend deployment failed! Check logs for details."
        # You could add Slack/Discord/email notifications here
